// src/src/app/custom-gas-input/custom-gas-input.component.ts
import { Component, EventEmitter, Input, Output, inject } from '@angular/core';
import { DivePlannerService } from '../dive-planner-service/DivePlannerService';
import { BreathingGas } from '../dive-planner-service/BreathingGas';
import { MatFormField, MatLabel, MatInput } from '@angular/material/input';
import { FormsModule } from '@angular/forms';
import { MatTooltip } from '@angular/material/tooltip';

@Component({
  selector: 'dive-custom-gas-input',
  templateUrl: './custom-gas-input.component.html',
  styleUrl: './custom-gas-input.component.scss',
  imports: [MatFormField, MatLabel, MatInput, FormsModule, MatTooltip],
})
export class CustomGasInputComponent {
  private divePlanner = inject(DivePlannerService);

  @Input() disabled: boolean = false;
  @Output() gasChanged = new EventEmitter<BreathingGas>();
  customGas: BreathingGas = BreathingGas.create(21, 0, 79, this.divePlanner.settings);

  onOxygenInput(): void {
    this.updateCustomGasNitrogen();
    this.gasChanged.emit(this.customGas);
  }

  onHeliumInput(): void {
    this.updateCustomGasNitrogen();
    this.gasChanged.emit(this.customGas);
  }

  private updateCustomGasNitrogen() {
    this.customGas.nitrogen = 100 - this.customGas.oxygen - this.customGas.helium;
    this.customGas = BreathingGas.create(this.customGas.oxygen, this.customGas.helium, this.customGas.nitrogen, this.divePlanner.settings);
  }
}

<div class="custom-gas-input">
  <mat-form-field>
    <mat-label>Oxygen (%)</mat-label>
    <input matInput type="number" min="0" max="100" [(ngModel)]="customGas.oxygen" (input)="onOxygenInput()" [disabled]="disabled" />
  </mat-form-field>
  <mat-form-field>
    <mat-label>Helium (%)</mat-label>
    <input matInput type="number" min="0" max="100" [(ngModel)]="customGas.helium" (input)="onHeliumInput()" [disabled]="disabled" />
  </mat-form-field>
  <mat-form-field matTooltip="The nitrogen value will be automatically calculated when you input the values for oxygen and helium">
    <mat-label>Nitrogen (%)</mat-label>
    <input matInput type="number" [(ngModel)]="customGas.nitrogen" disabled />
  </mat-form-field>
</div>

// src/src/components/CustomGasInput.tsx
'use client';

import { useState, useEffect } from 'react';
import { Box, TextField, Tooltip } from '@mui/material';
import { useDivePlanner, BreathingGas } from '@/context/DivePlannerContext';

interface CustomGasInputProps {
  disabled?: boolean;
  onGasChanged: (gas: BreathingGas) => void;
}

export default function CustomGasInput({ disabled = false, onGasChanged }: CustomGasInputProps) {
  const { divePlanner } = useDivePlanner();
  
  const [oxygen, setOxygen] = useState(21);
  const [helium, setHelium] = useState(0);
  const [nitrogen, setNitrogen] = useState(79);

  useEffect(() => {
    const newNitrogen = 100 - oxygen - helium;
    setNitrogen(newNitrogen);
    const gas = BreathingGas.create(oxygen, helium, newNitrogen, divePlanner.settings);
    onGasChanged(gas);
  }, [oxygen, helium, divePlanner.settings, onGasChanged]);

  return (
    <Box sx={{ display: 'flex', gap: 2, mt: 1 }}>
      <TextField
        label="Oxygen (%)"
        type="number"
        value={oxygen}
        onChange={(e) => setOxygen(Number(e.target.value))}
        disabled={disabled}
        inputProps={{ min: 0, max: 100 }}
        size="small"
      />
      <TextField
        label="Helium (%)"
        type="number"
        value={helium}
        onChange={(e) => setHelium(Number(e.target.value))}
        disabled={disabled}
        inputProps={{ min: 0, max: 100 }}
        size="small"
      />
      <Tooltip title="The nitrogen value will be automatically calculated when you input the values for oxygen and helium">
        <TextField
          label="Nitrogen (%)"
          type="number"
          value={nitrogen}
          disabled
          size="small"
        />
      </Tooltip>
    </Box>
  );
}
