// src/src/app/standard-gas-list/standard-gas-list.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { BreathingGas } from '../dive-planner-service/BreathingGas';
import { MatSelectionListChange } from '@angular/material/list';

@Component({
  selector: 'dive-standard-gas-list',
  templateUrl: './standard-gas-list.component.html',
  styleUrl: './standard-gas-list.component.scss',
})
export class StandardGasListComponent {
  @Input() disabled = false;
  @Output() gasSelected = new EventEmitter<BreathingGas>();

  standardGases: BreathingGas[] = BreathingGas.StandardGases;
  selectedGas: BreathingGas = this.standardGases[0];

  onGasChange(event: MatSelectionListChange): void {
    this.selectedGas = event.options[0].value;
    this.gasSelected.emit(this.selectedGas);
  }

  getGasTooltip(gas: BreathingGas): string {
    return `Max Depth (PO2): ${gas.maxDepthPO2}m (${gas.maxDepthPO2Deco}m deco)\nMax Depth (END): ${gas.maxDepthEND}m\nMin Depth (Hypoxia): ${gas.minDepth}m`;
  }
}

<mat-selection-list [multiple]="false" hideSingleSelectionIndicator (selectionChange)="onGasChange($event)" [disabled]="disabled">
  @for (gas of standardGases; track gas) {
    <mat-list-option
      [value]="gas"
      [selected]="gas === selectedGas"
      matTooltipClass="tooltip-multiline tooltip-wide"
      matTooltipPosition="left"
      [matTooltip]="getGasTooltip(gas)">
      <span matListItemTitle>{{ gas.name }}</span>
      <span matListItemLine [innerHTML]="gas.compositionDescription"></span>
    </mat-list-option>
  }
</mat-selection-list>

// src/src/components/StandardGasList.tsx
'use client';

import { useState } from 'react';
import {
  List,
  ListItemButton,
  ListItemText,
  Tooltip,
} from '@mui/material';
import { BreathingGas } from '@/services/dive-planner-service/BreathingGas';

interface StandardGasListProps {
  disabled?: boolean;
  onGasSelected: (gas: BreathingGas) => void;
}

export default function StandardGasList({ disabled = false, onGasSelected }: StandardGasListProps) {
  const standardGases = BreathingGas.StandardGases;
  const [selectedIndex, setSelectedIndex] = useState(0);

  const handleListItemClick = (index: number) => {
    setSelectedIndex(index);
    onGasSelected(standardGases[index]);
  };

  const getGasTooltip = (gas: BreathingGas): string => {
    return `Max Depth (PO2): ${gas.maxDepthPO2}m (${gas.maxDepthPO2Deco}m deco)\nMax Depth (END): ${gas.maxDepthEND}m\nMin Depth (Hypoxia): ${gas.minDepth}m`;
  };

  return (
    <List sx={{ width: '100%', maxWidth: 360, bgcolor: 'background.paper' }}>
      {standardGases.map((gas, index) => (
        <Tooltip key={gas.name} title={<span style={{ whiteSpace: 'pre-line' }}>{getGasTooltip(gas)}</span>} placement="right">
          <ListItemButton
            selected={selectedIndex === index}
            onClick={() => handleListItemClick(index)}
            disabled={disabled}
          >
            <ListItemText
              primary={gas.name}
              secondary={
                <span dangerouslySetInnerHTML={{ __html: gas.compositionDescription }} />
              }
            />
          </ListItemButton>
        </Tooltip>
      ))}
    </List>
  );
}
