// src/src/components/charts/TissuesPHeChart.tsx
'use client';

import { useMemo } from 'react';
import dynamic from 'next/dynamic';
import { Box, Paper } from '@mui/material';
import { useDivePlanner } from '@/context/DivePlannerContext';

const Plot = dynamic(() => import('react-plotly.js'), { ssr: false });

const PRIMARY_COLOR = '#3F51B5';
const TISSUE_COLORS = [
  '#FF6384', '#36A2EB', '#FFCE56', '#4BC0C0', '#9966FF',
  '#FF9F40', '#FF6384', '#C9CBCF', '#7BC225', '#E8C3B9',
  '#C45850', '#4D5360', '#949FB1', '#8E5EA2', '#3CBA9F', '#E8C3B9'
];

export default function TissuesPHeChart() {
  const { divePlanner, updateTrigger } = useDivePlanner();
  const segments = divePlanner.getDiveSegments();
  
  const showChart = segments.length > 2;

  const chartData = useMemo(() => {
    if (!showChart) return null;
    
    const data = divePlanner.getTissuesPHeChartData();
    const x = data.map(d => new Date(1970, 1, 1, 0, 0, d.time, 0));
    const gasPHe = data.map(d => d.gasPHe);

    const traces: Plotly.Data[] = [
      {
        x,
        y: gasPHe,
        type: 'scatter' as const,
        mode: 'lines' as const,
        name: 'Gas PHe',
        line: { color: PRIMARY_COLOR, width: 3 },
        hovertemplate: `%{y:.2f}`,
      },
    ];

    for (let i = 0; i < 16; i++) {
      traces.push({
        x,
        y: data.map(d => d.tissuesPHe[i]),
        type: 'scatter' as const,
        mode: 'lines' as const,
        name: `Tissue ${i + 1}`,
        line: { color: TISSUE_COLORS[i], width: 1 },
        hovertemplate: `%{y:.2f}`,
      });
    }

    return traces;
  }, [divePlanner, showChart, updateTrigger]);

  const layout = {
    autosize: true,
    showlegend: false,
    title: { text: 'Tissue PHe', y: 0.98 },
    margin: { l: 35, r: 10, b: 30, t: 20, pad: 10 },
    xaxis: { fixedrange: true, tickformat: '%H:%M:%S' },
    yaxis: { fixedrange: true },
    hovermode: 'x unified' as const,
  };

  const config = {
    responsive: true,
    displaylogo: false,
    displayModeBar: false,
  };

  if (!showChart) return null;

  return (
    <Paper elevation={2} sx={{ p: 2 }}>
      <Box sx={{ height: 300 }}>
        {chartData && (
          <Plot
            data={chartData}
            layout={layout}
            config={config}
            style={{ width: '100%', height: '100%' }}
          />
        )}
      </Box>
    </Paper>
  );
}

// src/src/app/tissues-phe-chart/tissues-phe-chart.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { DivePlannerService } from '../dive-planner-service/DivePlannerService';
import * as Plotly from 'plotly.js-basic-dist-min';
import { MatDialog } from '@angular/material/dialog';
import { GraphDialogComponent } from '../graph-dialog/graph-dialog.component';

@Component({
  selector: 'dive-tissues-phe-chart',
  templateUrl: './tissues-phe-chart.component.html',
  styleUrl: './tissues-phe-chart.component.scss',
})
export class TissuesPHeChartComponent implements OnInit {
  divePlanner = inject(DivePlannerService);
  dialog = inject(MatDialog);

  private readonly PRIMARY_COLOR = '#3F51B5';

  ngOnInit(): void {
    Plotly.newPlot('tissues-phe-chart', this.getTissuesPHeChartData(), this.getTissuesPHeChartLayout(), this.getChartOptions());
  }

  onTissuesPHeChartClick(): void {
    if (this.getShowGraphs()) {
      this.dialog.open(GraphDialogComponent, {
        data: { trace: this.getTissuesPHeChartData(), layout: this.getTissuesPHeChartLayout(), options: this.getChartOptions() },
        height: '80%',
        width: '80%',
      });
    }
  }

  getShowGraphs(): boolean {
    return this.divePlanner.getDiveSegments().length > 2;
  }

  getGraphClass(): string {
    return this.getShowGraphs() ? '' : 'hidden';
  }

  private chartData: Plotly.Data[] | null = null;

  private getTissuesPHeChartData(): Plotly.Data[] {
    if (!this.chartData) {
      const ceilingData = this.divePlanner.getTissuesPHeChartData();
      const x = ceilingData.map(d => new Date(1970, 1, 1, 0, 0, d.time, 0));

      const tissueTraces: Plotly.Data[] = [];

      for (let i = 1; i <= 16; i++) {
        tissueTraces.push({
          x,
          y: ceilingData.map(d => d.tissuesPHe[i - 1]),
          type: 'scatter',
          mode: 'lines',
          name: `Tissue ${i} PHe`,
          line: {
            width: 2,
          },
          hovertemplate: `%{y:.2f}`,
        });
      }

      this.chartData = [
        {
          x,
          y: ceilingData.map(d => d.gasPHe),
          type: 'scatter',
          mode: 'lines',
          name: 'Gas PHe',
          line: {
            color: this.PRIMARY_COLOR,
            width: 5,
          },
          hovertemplate: `%{y:.2f}`,
        },
        ...tissueTraces,
      ];
    }

    return this.chartData;
  }

  private getTissuesPHeChartLayout(): Partial<Plotly.Layout> {
    return {
      autosize: true,
      showlegend: false,
      title: {
        text: 'Tissues PHe vs Gas PHe',
        y: 0.98,
      },
      margin: { l: 35, r: 10, b: 30, t: 20, pad: 10 },
      xaxis: {
        fixedrange: true,
        tickformat: '%H:%M:%S',
      },
      yaxis: {
        fixedrange: true,
        rangemode: 'tozero',
        zeroline: false,
      },
      hovermode: 'x unified',
      hoverlabel: {
        bgcolor: 'rgba(200, 200, 200, 0.4)',
        bordercolor: 'rgba(200, 200, 200, 0.4)',
      },
    };
  }

  private getChartOptions(): Partial<Plotly.Config> {
    return {
      responsive: true,
      displaylogo: false,
      displayModeBar: false,
      autosizable: true,
      scrollZoom: false,
      editable: false,
    };
  }
}

<button (click)="onTissuesPHeChartClick()" class="graph mat-elevation-z2">
  <div id="tissues-phe-chart" class="plotly-graph" [class]="getGraphClass()"></div>
  @if (!getShowGraphs()) {
    <div>Create dive segements to populate graphs</div>
  }
</button>
