// src/app/components/NewGasStats.tsx
'use client';

import React, { useMemo } from 'react';
import { Box, Typography, Paper, Tooltip } from '@mui/material';
import WarningIcon from '@mui/icons-material/Warning';
import ErrorIcon from '@mui/icons-material/Error';
import { BreathingGas } from '../dive-planner-service/BreathingGas';
import { useDivePlanner } from '../contexts/DivePlannerContext';
import { humanDuration } from '../utility/formatters';
import { ceilingWithThreshold } from '../utility/utility';

interface NewGasStatsProps {
  newGas: BreathingGas;
}

export default function NewGasStats({ newGas }: NewGasStatsProps) {
  const { divePlanner, updateTrigger } = useDivePlanner();
  const settings = divePlanner.settings;
  const currentDepth = divePlanner.getCurrentDepth();

  const stats = useMemo(() => {
    const newGasPO2 = newGas.getPO2(currentDepth);
    const newGasEND = ceilingWithThreshold(newGas.getEND(currentDepth));

    const getPO2WarningMessage = () => divePlanner.getPO2WarningMessage(newGasPO2);
    const getPO2ErrorMessage = () => divePlanner.getPO2ErrorMessage(newGasPO2);
    const getENDErrorMessage = () => divePlanner.getENDErrorMessage(newGasEND);

    const getNoDecoLimit = () => {
      const ndl = divePlanner.getNoDecoLimit(currentDepth, newGas, 0);
      if (ndl === undefined) {
        return '> 5 hours';
      }
      return humanDuration(ndl);
    };

    return {
      newGasPO2,
      hasNewGasPO2Warning: getPO2WarningMessage() !== undefined,
      hasNewGasPO2Error: getPO2ErrorMessage() !== undefined,
      newGasPO2Warning: getPO2WarningMessage(),
      newGasPO2Error: getPO2ErrorMessage(),
      newGasEND,
      hasNewGasENDError: getENDErrorMessage() !== undefined,
      newGasENDError: getENDErrorMessage(),
      noDecoLimit: getNoDecoLimit(),
    };
  }, [newGas, currentDepth, divePlanner, updateTrigger]);

  return (
    <Paper elevation={2} sx={{ p: 2 }}>
      <Box sx={{ display: 'flex', gap: 4, flexWrap: 'wrap' }}>
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            <Tooltip title="Oxygen partial pressure of the new gas at the current depth" placement="top">
              <Typography>
                PO<sub>2</sub>: <strong>{stats.newGasPO2.toFixed(2)}</strong>
              </Typography>
            </Tooltip>
            {stats.hasNewGasPO2Warning && (
              <Tooltip title={stats.newGasPO2Warning} placement="right">
                <WarningIcon color="warning" />
              </Tooltip>
            )}
            {stats.hasNewGasPO2Error && (
              <Tooltip title={stats.newGasPO2Error} placement="right">
                <ErrorIcon color="error" />
              </Tooltip>
            )}
          </Box>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            <Tooltip title="Equivalent narcotic depth of the new gas at the current depth" placement="top">
              <Typography>
                END: <strong>{stats.newGasEND}m</strong>
              </Typography>
            </Tooltip>
            {stats.hasNewGasENDError && (
              <Tooltip title={stats.newGasENDError} placement="right">
                <ErrorIcon color="error" />
              </Tooltip>
            )}
          </Box>
          <Tooltip title="The amount of time you can stay at the current depth on the new gas and safely ascend directly to the surface (Note: this takes into account off-gassing that occurs during ascent)" placement="right">
            <Typography>
              No Deco Limit: <strong>{stats.noDecoLimit}</strong>
            </Typography>
          </Tooltip>
        </Box>
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
          <Tooltip title={settings.MaxDepthPO2Tooltip} placement="right">
            <Typography>
              Max Depth (PO<sub>2</sub>): <strong>{newGas.maxDepthPO2}m ({newGas.maxDepthPO2Deco}m deco)</strong>
            </Typography>
          </Tooltip>
          <Tooltip title={settings.MaxDepthENDTooltip} placement="right">
            <Typography>
              Max Depth (END): <strong>{newGas.maxDepthEND}m</strong>
            </Typography>
          </Tooltip>
          <Tooltip title={settings.MinDepthTooltip} placement="right">
            <Typography>
              Min Depth (Hypoxia): <strong>{newGas.minDepth}m</strong>
            </Typography>
          </Tooltip>
        </Box>
      </Box>
    </Paper>
  );
}

// src/src/app/new-gas-stats/new-gas-stats.component.ts
import { Component, Input, OnChanges } from '@angular/core';
import { BreathingGas } from '../dive-planner-service/BreathingGas';
import { DivePlannerService } from '../dive-planner-service/DivePlannerService';
import { HumanDurationPipe } from '../pipes/human-duration.pipe';
import { ceilingWithThreshold } from '../utility/utility';

@Component({
  selector: 'dive-new-gas-stats',
  templateUrl: './new-gas-stats.component.html',
  styleUrl: './new-gas-stats.component.scss',
})
export class NewGasStatsComponent implements OnChanges {
  @Input() newGas: BreathingGas = this.divePlanner.getCurrentGas();

  currentDepth: number = this.divePlanner.getCurrentDepth();
  newGasPO2: number = this.getNewGasPO2();
  hasNewGasPO2Warning: boolean = this.getNewGasPO2WarningMessage() !== undefined;
  hasNewGasPO2Error: boolean = this.getNewGasPO2ErrorMessage() !== undefined;
  newGasPO2Warning: string | undefined = this.getNewGasPO2WarningMessage();
  newGasPO2Error: string | undefined = this.getNewGasPO2ErrorMessage();
  newGasEND: number = this.getNewGasEND();
  hasNewGasENDError: boolean = this.getNewGasENDErrorMessage() !== undefined;
  newGasENDError: string | undefined = this.getNewGasENDErrorMessage();
  noDecoLimit: string = this.getNoDecoLimit();

  constructor(
    public divePlanner: DivePlannerService,
    private humanDurationPipe: HumanDurationPipe
  ) {}

  ngOnChanges(): void {
    this.calculateNewGasStats();
  }

  private calculateNewGasStats(): void {
    this.newGasPO2 = this.getNewGasPO2();
    this.hasNewGasPO2Warning = this.getNewGasPO2WarningMessage() !== undefined;
    this.hasNewGasPO2Error = this.getNewGasPO2ErrorMessage() !== undefined;
    this.newGasPO2Warning = this.getNewGasPO2WarningMessage();
    this.newGasPO2Error = this.getNewGasPO2ErrorMessage();
    this.newGasEND = this.getNewGasEND();
    this.hasNewGasENDError = this.getNewGasENDErrorMessage() !== undefined;
    this.newGasENDError = this.getNewGasENDErrorMessage();
    this.noDecoLimit = this.getNoDecoLimit();
  }

  private getNewGasPO2(): number {
    return this.newGas.getPO2(this.currentDepth);
  }

  private getNewGasPO2WarningMessage(): string | undefined {
    return this.divePlanner.getPO2WarningMessage(this.getNewGasPO2());
  }

  private getNewGasPO2ErrorMessage(): string | undefined {
    return this.divePlanner.getPO2ErrorMessage(this.getNewGasPO2());
  }

  private getNewGasEND(): number {
    return ceilingWithThreshold(this.newGas.getEND(this.currentDepth));
  }

  private getNewGasENDErrorMessage(): string | undefined {
    return this.divePlanner.getENDErrorMessage(this.getNewGasEND());
  }

  private getNoDecoLimit(): string {
    const ndl = this.divePlanner.getNoDecoLimit(this.currentDepth, this.newGas);

    if (ndl === undefined) {
      return '> 5 hours';
    }

    return this.humanDurationPipe.transform(ndl);
  }
}

<div class="new-gas-stats">
  <div class="gas-calculation-chunk">
    <div class="dive-stat">
      <span matTooltip="Oxygen partial pressure of the new gas at the current depth" matTooltipPosition="above">
        <!-- eslint-disable-next-line prettier/prettier -->
        PO<sub>2</sub>:
        <strong>{{ newGasPO2 | number: '1.2-2' }}</strong>
      </span>
      @if (hasNewGasPO2Warning) {
        <mat-icon class="warning-icon" [matTooltip]="newGasPO2Warning!" matTooltipPosition="right">warning</mat-icon>
      }
      @if (hasNewGasPO2Error) {
        <mat-icon class="error-icon" [matTooltip]="newGasPO2Error!" matTooltipPosition="right">error</mat-icon>
      }
    </div>
    <div class="dive-stat">
      <span matTooltip="Equivalent narcotic depth of the new gas at the current depth" matTooltipPosition="above">
        END:
        <strong>{{ newGasEND }}m</strong>
      </span>
      @if (hasNewGasENDError) {
        <mat-icon class="error-icon" [matTooltip]="newGasENDError!" matTooltipPosition="right">error</mat-icon>
      }
    </div>
    <div class="dive-stat">
      <span
        matTooltip="The amount of time you can stay at the current depth on the new gas and safely ascend directly to the surface (Note: this takes into account off-gassing that occurs during ascent)"
        matTooltipPosition="right">
        No Deco Limit:
        <strong>{{ noDecoLimit }}</strong>
      </span>
    </div>
  </div>
  <div class="gas-calculation-chunk">
    <div class="dive-stat">
      <span [matTooltip]="divePlanner.settings.MaxDepthPO2Tooltip" matTooltipPosition="right">
        <!-- eslint-disable-next-line prettier/prettier -->
        Max Depth (PO<sub>2</sub>):
        <strong>{{ newGas.maxDepthPO2 }}m ({{ newGas.maxDepthPO2Deco }}m deco)</strong>
      </span>
    </div>
    <div class="dive-stat">
      <span [matTooltip]="divePlanner.settings.MaxDepthENDTooltip" matTooltipPosition="right">
        Max Depth (END):
        <strong>{{ newGas.maxDepthEND }}m</strong>
      </span>
    </div>
    <div class="dive-stat">
      <span [matTooltip]="divePlanner.settings.MinDepthTooltip" matTooltipPosition="right">
        Min Depth (Hypoxia):
        <strong>{{ newGas.minDepth }}m</strong>
      </span>
    </div>
  </div>
</div>
