// src/src/app/(routes)/new-dive/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import {
  Box,
  Button,
  FormControl,
  FormControlLabel,
  Radio,
  RadioGroup,
  Typography,
  Paper,
} from '@mui/material';
import { useDivePlanner, BreathingGas } from '@/context/DivePlannerContext';
import StandardGasList from '@/components/StandardGasList';
import CustomGasInput from '@/components/CustomGasInput';
import DiveSettings from '@/components/DiveSettings';
import StartGasStats from '@/components/StartGasStats';

export default function NewDivePage() {
  const router = useRouter();
  const { divePlanner, triggerUpdate } = useDivePlanner();

  const [gasType, setGasType] = useState<'standard' | 'custom'>('standard');
  const [selectedStandardGas, setSelectedStandardGas] = useState<BreathingGas>(
    BreathingGas.StandardGases[0]
  );
  const [customGas, setCustomGas] = useState<BreathingGas>(
    BreathingGas.create(21, 0, 79, divePlanner.settings)
  );

  const getSelectedGas = () => {
    return gasType === 'standard' ? selectedStandardGas : customGas;
  };

  const handleSave = () => {
    divePlanner.startDive(getSelectedGas());
    triggerUpdate();
    router.push('/dive-overview');
  };

  return (
    <Box component="main" sx={{ p: 2 }}>
      <Typography variant="h5" component="h1" id="select-starting-gas-heading" sx={{ mb: 3 }}>
        Select the starting gas for the dive
      </Typography>

      <FormControl component="fieldset">
        <RadioGroup
          aria-labelledby="select-starting-gas-heading"
          value={gasType}
          onChange={(e) => setGasType(e.target.value as 'standard' | 'custom')}
        >
          <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 3 }}>
            <Box>
              <FormControlLabel
                value="standard"
                control={<Radio />}
                label="Standard gas"
              />
              <Paper elevation={2} sx={{ p: 2, mt: 1 }}>
                <StandardGasList
                  disabled={gasType === 'custom'}
                  onGasSelected={setSelectedStandardGas}
                />
              </Paper>
            </Box>

            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
              <Box>
                <FormControlLabel
                  value="custom"
                  control={<Radio />}
                  label="Custom gas"
                />
                <CustomGasInput
                  disabled={gasType === 'standard'}
                  onGasChanged={setCustomGas}
                />
              </Box>
              <Paper elevation={2} sx={{ p: 2 }}>
                <DiveSettings />
              </Paper>
            </Box>

            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
              <Paper elevation={2} sx={{ p: 2 }}>
                <StartGasStats gas={getSelectedGas()} />
              </Paper>
              <Box>
                <Button
                  variant="contained"
                  color="primary"
                  onClick={handleSave}
                >
                  Save
                </Button>
              </Box>
            </Box>
          </Box>
        </RadioGroup>
      </FormControl>
    </Box>
  );
}

// src/src/app/new-dive/new-dive.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { BreathingGas } from '../dive-planner-service/BreathingGas';
import { DivePlannerService } from '../dive-planner-service/DivePlannerService';

@Component({
  selector: 'dive-new-dive',
  templateUrl: './new-dive.component.html',
  styleUrls: ['./new-dive.component.scss'],
})
export class NewDiveComponent {
  constructor(
    private router: Router,
    public divePlanner: DivePlannerService
  ) {}

  selectedStandardGas: BreathingGas = BreathingGas.StandardGases[0];
  gasType = 'standard';
  customGas: BreathingGas = BreathingGas.create(21, 0, 79, this.divePlanner.settings);

  getCustomGasDisabled() {
    return this.gasType === 'standard';
  }

  getStandardGasDisabled() {
    return this.gasType === 'custom';
  }

  onStandardGasSelected(gas: BreathingGas): void {
    this.selectedStandardGas = gas;
  }

  onCustomGasChanged(gas: BreathingGas): void {
    this.customGas = gas;
  }

  getSelectedGas() {
    if (this.gasType === 'standard') {
      return this.selectedStandardGas;
    } else {
      return this.customGas;
    }
  }

  onSave() {
    this.divePlanner.startDive(this.getSelectedGas());
    this.router.navigate(['/dive-overview']);
  }
}

<main>
  <header>
    <h1 id="select-starting-gas-heading">Select the starting gas for the dive</h1>
  </header>
  <mat-radio-group aria-labelledby="select-starting-gas-heading" [(ngModel)]="gasType">
    <div class="standard-gas">
      <div class="radio-button">
        <mat-radio-button name="gasType" value="standard">Standard gas</mat-radio-button>
      </div>
      <dive-standard-gas-list
        (gasSelected)="onStandardGasSelected($event)"
        [disabled]="getStandardGasDisabled()"
        class="mat-elevation-z2"></dive-standard-gas-list>
    </div>
    <div class="custom-gas-col">
      <div class="custom-gas">
        <div class="radio-button">
          <mat-radio-button value="custom">Custom gas</mat-radio-button>
        </div>
        <dive-custom-gas-input (gasChanged)="onCustomGasChanged($event)" [disabled]="getCustomGasDisabled()"></dive-custom-gas-input>
      </div>
      <dive-dive-settings class="mat-elevation-z2"></dive-dive-settings>
    </div>
    <div class="summary-data">
      <dive-start-gas-stats class="mat-elevation-z2" [gas]="getSelectedGas()"></dive-start-gas-stats>
      <div class="save-section">
        <button mat-flat-button color="primary" (click)="onSave()">Save</button>
      </div>
    </div>
  </mat-radio-group>
</main>
