// src/src/app/current-stats/current-stats.component.ts
import { Component } from '@angular/core';
import { DivePlannerService } from '../dive-planner-service/DivePlannerService';
import { BreathingGas } from '../dive-planner-service/BreathingGas';
import { ceilingWithThreshold } from '../utility/utility';
import { HumanDurationPipe } from '../pipes/human-duration.pipe';

@Component({
  selector: 'dive-current-stats',
  templateUrl: './current-stats.component.html',
  styleUrl: './current-stats.component.scss',
})
export class CurrentStatsComponent {
  currentDepth: number = this.divePlanner.getCurrentDepth();
  currentGas: BreathingGas = this.divePlanner.getCurrentGas();
  noDecoLimit: string = this.getNoDecoLimit();
  currentCeiling: number = this.divePlanner.getCurrentCeiling();
  instantCeiling: number = this.divePlanner.getCurrentInstantCeiling();
  currentPO2: number = this.getPO2();
  hasCurrentPO2Warning: boolean = this.getPO2WarningMessage() !== undefined;
  hasCurrentPO2Error: boolean = this.getPO2ErrorMessage() !== undefined;
  currentPO2Warning: string | undefined = this.getPO2WarningMessage();
  currentPO2Error: string | undefined = this.getPO2ErrorMessage();
  currentEND: number = this.getEND();
  hasCurrentENDError: boolean = this.getENDErrorMessage() !== undefined;
  currentENDError: string | undefined = this.getENDErrorMessage();

  constructor(
    public divePlanner: DivePlannerService,
    private humanDurationPipe: HumanDurationPipe
  ) {}

  private getPO2(): number {
    return this.currentGas.getPO2(this.currentDepth);
  }

  private getPO2WarningMessage(): string | undefined {
    return this.divePlanner.getPO2WarningMessage(this.getPO2());
  }

  private getPO2ErrorMessage(): string | undefined {
    return this.divePlanner.getPO2ErrorMessage(this.getPO2());
  }

  private getEND(): number {
    return ceilingWithThreshold(this.currentGas.getEND(this.currentDepth));
  }

  private getENDErrorMessage(): string | undefined {
    return this.divePlanner.getENDErrorMessage(this.getEND());
  }

  private getNoDecoLimit(): string {
    const ndl = this.divePlanner.getNoDecoLimit(this.currentDepth, this.currentGas, 0);

    if (ndl === undefined) {
      return '> 5 hours';
    }

    return this.humanDurationPipe.transform(ndl);
  }
}

<div class="current-stats">
  <div class="dive-stat">
    Current Depth:
    <strong>{{ currentDepth }}m</strong>
  </div>
  <div class="dive-stat">
    <span
      matTooltip="The amount of time you can stay at the current depth on the current gas and safely ascend directly to the surface (Note: this takes into account off-gassing that occurs during ascent)"
      matTooltipPosition="right">
      No Deco Limit:
      <strong>{{ noDecoLimit }}</strong>
    </span>
  </div>
  <div class="dive-stat">
    <span
      matTooltip="The shallowest depth you can safely ascend directly to. This takes into account any on/off-gassing that may occur during the ascent. (Instantaneous Ceiling = {{
        instantCeiling
      }}m)"
      matTooltipPosition="right">
      Current Ceiling:
      <strong>{{ currentCeiling }}m</strong>
    </span>
  </div>
  <div class="dive-stat">
    Current Gas:
    <strong [innerHTML]="currentGas.description"></strong>
  </div>
  <div class="gas-stat dive-stat">
    <span [matTooltip]="divePlanner.settings.MaxDepthPO2Tooltip" matTooltipPosition="right">
      <!-- eslint-disable-next-line prettier/prettier -->
      Max Depth (PO<sub>2</sub>):
      <strong>{{ currentGas.maxDepthPO2 }}m ({{ currentGas.maxDepthPO2Deco }}m deco)</strong>
    </span>
  </div>
  <div class="gas-stat dive-stat">
    <span [matTooltip]="divePlanner.settings.MaxDepthENDTooltip" matTooltipPosition="right">
      Max Depth (END):
      <strong>{{ currentGas.maxDepthEND }}m</strong>
    </span>
  </div>
  <div class="gas-stat dive-stat">
    <span [matTooltip]="divePlanner.settings.MinDepthTooltip" matTooltipPosition="right">
      Min Depth (Hypoxia):
      <strong>{{ currentGas.minDepth }}m</strong>
    </span>
  </div>
  <div class="dive-stat">
    <span matTooltip="Oxygen partial pressure of the current gas at the current depth" matTooltipPosition="right">
      <!-- eslint-disable-next-line prettier/prettier -->
      PO<sub>2</sub>:
      <strong>{{ currentPO2 | number: '1.2-2' }}</strong>
    </span>
    @if (hasCurrentPO2Warning) {
      <mat-icon class="warning-icon" [matTooltip]="currentPO2Warning!" matTooltipPosition="right">warning</mat-icon>
    }
    @if (hasCurrentPO2Error) {
      <mat-icon class="error-icon" [matTooltip]="currentPO2Error!" matTooltipPosition="right">error</mat-icon>
    }
  </div>
  <div class="dive-stat">
    <span matTooltip="Equivalent narcotic depth of the current gas at the current depth" matTooltipPosition="right">
      END:
      <strong>{{ currentEND }}m</strong>
    </span>
    @if (hasCurrentENDError) {
      <mat-icon class="error-icon" [matTooltip]="currentENDError!" matTooltipPosition="right">error</mat-icon>
    }
  </div>
</div>

// src/app/components/CurrentStats.tsx
'use client';

import React from 'react';
import { Box, Typography, Paper, Tooltip } from '@mui/material';
import WarningIcon from '@mui/icons-material/Warning';
import ErrorIcon from '@mui/icons-material/Error';
import { useDivePlanner } from '../contexts/DivePlannerContext';
import { humanDuration } from '../utility/formatters';
import { ceilingWithThreshold } from '../utility/utility';

export default function CurrentStats() {
  const { divePlanner, updateTrigger } = useDivePlanner();

  const currentDepth = divePlanner.getCurrentDepth();
  const currentGas = divePlanner.getCurrentGas();
  const currentCeiling = divePlanner.getCurrentCeiling();
  const instantCeiling = divePlanner.getCurrentInstantCeiling();
  const settings = divePlanner.settings;

  const getPO2 = () => currentGas.getPO2(currentDepth);
  const getEND = () => ceilingWithThreshold(currentGas.getEND(currentDepth));

  const getPO2WarningMessage = () => divePlanner.getPO2WarningMessage(getPO2());
  const getPO2ErrorMessage = () => divePlanner.getPO2ErrorMessage(getPO2());
  const getENDErrorMessage = () => divePlanner.getENDErrorMessage(getEND());

  const getNoDecoLimit = () => {
    const ndl = divePlanner.getNoDecoLimit(currentDepth, currentGas, 0);
    if (ndl === undefined) {
      return '> 5 hours';
    }
    return humanDuration(ndl);
  };

  const hasCurrentPO2Warning = getPO2WarningMessage() !== undefined;
  const hasCurrentPO2Error = getPO2ErrorMessage() !== undefined;
  const hasCurrentENDError = getENDErrorMessage() !== undefined;

  return (
    <Paper elevation={2} sx={{ p: 2, mb: 2 }}>
      <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
        <Typography>
          Current Depth: <strong>{currentDepth}m</strong>
        </Typography>
        <Tooltip title="The amount of time you can stay at the current depth on the current gas and safely ascend directly to the surface (Note: this takes into account off-gassing that occurs during ascent)" placement="right">
          <Typography>
            No Deco Limit: <strong>{getNoDecoLimit()}</strong>
          </Typography>
        </Tooltip>
        <Tooltip title={`The shallowest depth you can safely ascend directly to. This takes into account any on/off-gassing that may occur during the ascent. (Instantaneous Ceiling = ${instantCeiling}m)`} placement="right">
          <Typography>
            Current Ceiling: <strong>{currentCeiling}m</strong>
          </Typography>
        </Tooltip>
        <Typography>
          Current Gas: <strong dangerouslySetInnerHTML={{ __html: currentGas.description }} />
        </Typography>
        <Tooltip title={settings.MaxDepthPO2Tooltip} placement="right">
          <Typography>
            Max Depth (PO<sub>2</sub>): <strong>{currentGas.maxDepthPO2}m ({currentGas.maxDepthPO2Deco}m deco)</strong>
          </Typography>
        </Tooltip>
        <Tooltip title={settings.MaxDepthENDTooltip} placement="right">
          <Typography>
            Max Depth (END): <strong>{currentGas.maxDepthEND}m</strong>
          </Typography>
        </Tooltip>
        <Tooltip title={settings.MinDepthTooltip} placement="right">
          <Typography>
            Min Depth (Hypoxia): <strong>{currentGas.minDepth}m</strong>
          </Typography>
        </Tooltip>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <Tooltip title="Oxygen partial pressure of the current gas at the current depth" placement="right">
            <Typography>
              PO<sub>2</sub>: <strong>{getPO2().toFixed(2)}</strong>
            </Typography>
          </Tooltip>
          {hasCurrentPO2Warning && (
            <Tooltip title={getPO2WarningMessage()} placement="right">
              <WarningIcon color="warning" />
            </Tooltip>
          )}
          {hasCurrentPO2Error && (
            <Tooltip title={getPO2ErrorMessage()} placement="right">
              <ErrorIcon color="error" />
            </Tooltip>
          )}
        </Box>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <Tooltip title="Equivalent narcotic depth of the current gas at the current depth" placement="right">
            <Typography>
              END: <strong>{getEND()}m</strong>
            </Typography>
          </Tooltip>
          {hasCurrentENDError && (
            <Tooltip title={getENDErrorMessage()} placement="right">
              <ErrorIcon color="error" />
            </Tooltip>
          )}
        </Box>
      </Box>
    </Paper>
  );
}
