// src/src/app/error-list/error-list.component.ts
import { Component } from '@angular/core';
import { DivePlannerService } from '../dive-planner-service/DivePlannerService';

@Component({
  selector: 'dive-error-list',
  templateUrl: './error-list.component.html',
  styleUrl: './error-list.component.scss',
})
export class ErrorListComponent {
  constructor(public divePlanner: DivePlannerService) {}

  public getCeilingErrorAmount(): number {
    return this.divePlanner.getCeilingError().amount;
  }

  public getCeilingErrorDuration(): number {
    return this.divePlanner.getCeilingError().duration;
  }

  public showCeilingError(): boolean {
    return this.getCeilingErrorDuration() > 0;
  }

  public getPO2ErrorAmount(): number {
    return this.divePlanner.getPO2Error().maxPO2;
  }

  public getPO2ErrorDuration(): number {
    return this.divePlanner.getPO2Error().duration;
  }

  public showPO2Error(): boolean {
    return this.getPO2ErrorDuration() > 0;
  }

  public getHypoxicErrorAmount(): number {
    return this.divePlanner.getHypoxicError().minPO2;
  }

  public getHypoxicErrorDuration(): number {
    return this.divePlanner.getHypoxicError().duration;
  }

  public showHypoxicError(): boolean {
    return this.getHypoxicErrorDuration() > 0;
  }

  public getENDErrorAmount(): number {
    return this.divePlanner.getENDError().end;
  }

  public getENDErrorDuration(): number {
    return this.divePlanner.getENDError().duration;
  }

  public showENDError(): boolean {
    return this.getENDErrorDuration() > 0;
  }
}

<div class="errors">
  @if (showCeilingError()) {
    <div class="plan-error">
      <mat-icon>error</mat-icon>
      <strong class="error-message">
        Exceeded ceiling by up to {{ getCeilingErrorAmount() | number: '1.1-1' }}m for {{ getCeilingErrorDuration() | humanDuration }}
      </strong>
    </div>
  }
  @if (showPO2Error()) {
    <div class="plan-error">
      <mat-icon>error</mat-icon>
      <strong class="error-message">
        Exceeded safe PO2 for {{ getPO2ErrorDuration() | humanDuration }}, up to PO2 = {{ getPO2ErrorAmount() | number: '1.2-2' }}
      </strong>
    </div>
  }
  @if (showHypoxicError()) {
    <div class="plan-error">
      <mat-icon>error</mat-icon>
      <strong class="error-message">
        Hypoxic gas as low as {{ getHypoxicErrorAmount() | number: '1.3-3' }} for {{ getHypoxicErrorDuration() | humanDuration }}
      </strong>
    </div>
  }
  @if (showENDError()) {
    <div class="plan-error">
      <mat-icon>error</mat-icon>
      <strong class="error-message">
        <!-- eslint-disable-next-line prettier/prettier -->
        END as deep as {{ getENDErrorAmount() | number: '1.1-1' }}m for {{ getENDErrorDuration() | humanDuration }}
      </strong>
    </div>
  }
</div>

// src/app/components/ErrorList.tsx
'use client';

import React from 'react';
import { Box, Typography, Paper } from '@mui/material';
import ErrorIcon from '@mui/icons-material/Error';
import { useDivePlanner } from '../contexts/DivePlannerContext';
import { humanDuration } from '../utility/formatters';

export default function ErrorList() {
  const { divePlanner, updateTrigger } = useDivePlanner();

  const getCeilingError = () => divePlanner.getCeilingError();
  const getPO2Error = () => divePlanner.getPO2Error();
  const getHypoxicError = () => divePlanner.getHypoxicError();
  const getENDError = () => divePlanner.getENDError();

  const showCeilingError = () => getCeilingError().duration > 0;
  const showPO2Error = () => getPO2Error().duration > 0;
  const showHypoxicError = () => getHypoxicError().duration > 0;
  const showENDError = () => getENDError().duration > 0;

  const hasErrors = showCeilingError() || showPO2Error() || showHypoxicError() || showENDError();

  if (!hasErrors) {
    return null;
  }

  return (
    <Paper elevation={2} sx={{ p: 2, mb: 2 }}>
      <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
        {showCeilingError() && (
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, color: 'error.main' }}>
            <ErrorIcon />
            <Typography>
              <strong>
                Exceeded ceiling by up to {getCeilingError().amount.toFixed(1)}m for {humanDuration(getCeilingError().duration)}
              </strong>
            </Typography>
          </Box>
        )}
        {showPO2Error() && (
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, color: 'error.main' }}>
            <ErrorIcon />
            <Typography>
              <strong>
                Exceeded safe PO2 for {humanDuration(getPO2Error().duration)}, up to PO2 = {getPO2Error().maxPO2.toFixed(2)}
              </strong>
            </Typography>
          </Box>
        )}
        {showHypoxicError() && (
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, color: 'error.main' }}>
            <ErrorIcon />
            <Typography>
              <strong>
                Hypoxic gas as low as {getHypoxicError().minPO2.toFixed(3)} for {humanDuration(getHypoxicError().duration)}
              </strong>
            </Typography>
          </Box>
        )}
        {showENDError() && (
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, color: 'error.main' }}>
            <ErrorIcon />
            <Typography>
              <strong>
                END as deep as {getENDError().end.toFixed(1)}m for {humanDuration(getENDError().duration)}
              </strong>
            </Typography>
          </Box>
        )}
      </Box>
    </Paper>
  );
}
