// src/DivingCalculator.Web/src/app/new-depth-stats/new-depth-stats.component.ts
import { Component, Input, OnChanges } from '@angular/core';
import { DivePlannerService } from '../dive-planner-service/DivePlannerService';
import { ceilingWithThreshold } from '../utility/utility';

@Component({
  selector: 'dive-new-depth-stats',
  templateUrl: './new-depth-stats.component.html',
  styleUrl: './new-depth-stats.component.scss',
})
export class NewDepthStatsComponent implements OnChanges {
  @Input() newDepth: number = 0;

  travelTime: number = this.divePlanner.getTravelTime(this.newDepth);
  descentRate: number = this.divePlanner.settings.descentRate;
  ascentRate: number = this.divePlanner.settings.ascentRate;
  isDescent: boolean = this.isNewDepthDescent();
  isAscent = !this.isNewDepthDescent();
  PO2: number = this.getPO2();
  hasPO2Warning: boolean = this.getPO2WarningMessage() !== undefined;
  hasPO2Error: boolean = this.getPO2ErrorMessage() !== undefined;
  PO2WarningMessage: string | undefined = this.getPO2WarningMessage();
  PO2ErrorMessage: string | undefined = this.getPO2ErrorMessage();
  END: number = this.getEND();
  hasENDError: boolean = this.getENDErrorMessage() !== undefined;
  ENDErrorMessage: string | undefined = this.getENDErrorMessage();

  constructor(public divePlanner: DivePlannerService) {}

  ngOnChanges(): void {
    this.calculateNewDepthStats();
  }

  private calculateNewDepthStats(): void {
    this.travelTime = this.divePlanner.getTravelTime(this.newDepth);
    this.isDescent = this.isNewDepthDescent();
    this.isAscent = !this.isNewDepthDescent();
    this.PO2 = this.getPO2();
    this.hasPO2Warning = this.getPO2WarningMessage() !== undefined;
    this.hasPO2Error = this.getPO2ErrorMessage() !== undefined;
    this.PO2WarningMessage = this.getPO2WarningMessage();
    this.PO2ErrorMessage = this.getPO2ErrorMessage();
    this.END = this.getEND();
    this.hasENDError = this.getENDErrorMessage() !== undefined;
    this.ENDErrorMessage = this.getENDErrorMessage();
  }

  private isNewDepthDescent(): boolean {
    return this.newDepth >= this.divePlanner.getCurrentDepth();
  }

  private getPO2(): number {
    return this.divePlanner.getCurrentGas().getPO2(this.newDepth);
  }

  private getPO2WarningMessage(): string | undefined {
    return this.divePlanner.getPO2WarningMessage(this.getPO2());
  }

  private getPO2ErrorMessage(): string | undefined {
    return this.divePlanner.getPO2ErrorMessage(this.getPO2());
  }

  private getEND(): number {
    return ceilingWithThreshold(this.divePlanner.getCurrentGas().getEND(this.newDepth));
  }

  private getENDErrorMessage(): string | undefined {
    return this.divePlanner.getENDErrorMessage(this.getEND());
  }
}

<div class="new-depth-stats">
  <div class="dive-stat" *ngIf="isDescent">
    Descent Time:
    <strong>{{ travelTime | humanDuration }} &#64; {{ descentRate }}m/min</strong>
  </div>
  <div class="dive-stat" *ngIf="isAscent">
    Ascent Time:
    <strong>{{ travelTime | humanDuration }} &#64; {{ ascentRate }}m/min</strong>
  </div>
  <div class="dive-stat">
    <span matTooltip="Oxygen partial pressure of the current gas at the new depth" matTooltipPosition="above">
      <!-- eslint-disable-next-line prettier/prettier -->
      PO<sub>2</sub>:
      <strong>{{ PO2 | number: '1.2-2' }}</strong>
    </span>
    <mat-icon *ngIf="hasPO2Warning" class="warning-icon" [matTooltip]="PO2WarningMessage!" matTooltipPosition="right">warning</mat-icon>
    <mat-icon *ngIf="hasPO2Error" class="error-icon" [matTooltip]="PO2ErrorMessage!" matTooltipPosition="right">error</mat-icon>
  </div>
  <div class="dive-stat">
    <span matTooltip="Equivalent narcotic depth of the current gas at the new depth" matTooltipPosition="above">
      END:
      <strong>{{ END }}m</strong>
    </span>
    <mat-icon *ngIf="hasENDError" class="error-icon" [matTooltip]="ENDErrorMessage!" matTooltipPosition="right">error</mat-icon>
  </div>
</div>

// src/app/components/NewDepthStats.tsx
'use client';

import React, { useMemo } from 'react';
import { Box, Typography, Paper, Tooltip } from '@mui/material';
import WarningIcon from '@mui/icons-material/Warning';
import ErrorIcon from '@mui/icons-material/Error';
import { useDivePlanner } from '../contexts/DivePlannerContext';
import { humanDuration } from '../utility/formatters';
import { ceilingWithThreshold } from '../utility/utility';

interface NewDepthStatsProps {
  newDepth: number;
}

export default function NewDepthStats({ newDepth }: NewDepthStatsProps) {
  const { divePlanner, updateTrigger } = useDivePlanner();
  const settings = divePlanner.settings;

  const stats = useMemo(() => {
    const currentGas = divePlanner.getCurrentGas();
    const currentDepth = divePlanner.getCurrentDepth();
    const travelTime = divePlanner.getTravelTime(newDepth);
    const isDescent = newDepth >= currentDepth;
    const PO2 = currentGas.getPO2(newDepth);
    const END = ceilingWithThreshold(currentGas.getEND(newDepth));

    const getPO2WarningMessage = () => divePlanner.getPO2WarningMessage(PO2);
    const getPO2ErrorMessage = () => divePlanner.getPO2ErrorMessage(PO2);
    const getENDErrorMessage = () => divePlanner.getENDErrorMessage(END);

    const getNoDecoLimit = () => {
      const ndl = divePlanner.getNoDecoLimit(newDepth, currentGas, 0);
      if (ndl === undefined) {
        return '> 5 hours';
      }
      return humanDuration(ndl);
    };

    return {
      travelTime,
      descentRate: settings.descentRate,
      ascentRate: settings.ascentRate,
      isDescent,
      isAscent: !isDescent,
      PO2,
      hasPO2Warning: getPO2WarningMessage() !== undefined,
      hasPO2Error: getPO2ErrorMessage() !== undefined,
      PO2WarningMessage: getPO2WarningMessage(),
      PO2ErrorMessage: getPO2ErrorMessage(),
      END,
      hasENDError: getENDErrorMessage() !== undefined,
      ENDErrorMessage: getENDErrorMessage(),
      noDecoLimit: getNoDecoLimit(),
      ceiling: divePlanner.getNewCeiling(newDepth, 0),
      instantCeiling: divePlanner.getNewInstantCeiling(newDepth, 0),
    };
  }, [newDepth, divePlanner, settings, updateTrigger]);

  return (
    <Paper elevation={2} sx={{ p: 2 }}>
      <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
        {stats.isDescent ? (
          <Typography>
            Descent Time: <strong>{humanDuration(stats.travelTime)} @ {stats.descentRate}m/min</strong>
          </Typography>
        ) : (
          <Typography>
            Ascent Time: <strong>{humanDuration(stats.travelTime)} @ {stats.ascentRate}m/min</strong>
          </Typography>
        )}
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <Tooltip title="Oxygen partial pressure of the current gas at the new depth" placement="top">
            <Typography>
              PO<sub>2</sub>: <strong>{stats.PO2.toFixed(2)}</strong>
            </Typography>
          </Tooltip>
          {stats.hasPO2Warning && (
            <Tooltip title={stats.PO2WarningMessage} placement="right">
              <WarningIcon color="warning" />
            </Tooltip>
          )}
          {stats.hasPO2Error && (
            <Tooltip title={stats.PO2ErrorMessage} placement="right">
              <ErrorIcon color="error" />
            </Tooltip>
          )}
        </Box>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <Tooltip title="Equivalent narcotic depth of the current gas at the new depth" placement="top">
            <Typography>
              END: <strong>{stats.END}m</strong>
            </Typography>
          </Tooltip>
          {stats.hasENDError && (
            <Tooltip title={stats.ENDErrorMessage} placement="right">
              <ErrorIcon color="error" />
            </Tooltip>
          )}
        </Box>
        <Tooltip title="The amount of time you can stay at the new depth on the current gas and safely ascend directly to the surface (Note: this takes into account off-gassing that occurs during ascent)" placement="right">
          <Typography>
            No Deco Limit: <strong>{stats.noDecoLimit}</strong>
          </Typography>
        </Tooltip>
        <Tooltip title={`The shallowest depth you can safely ascend directly to. This takes into account any on/off-gassing that may occur during the ascent. (Instantaneous Ceiling = ${stats.instantCeiling}m)`} placement="right">
          <Typography>
            Ceiling: <strong>{stats.ceiling}m</strong>
          </Typography>
        </Tooltip>
      </Box>
    </Paper>
  );
}
