// src/src/app/new-gas-input/new-gas-input.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { DivePlannerService } from '../dive-planner-service/DivePlannerService';
import { BreathingGas } from '../dive-planner-service/BreathingGas';

@Component({
  selector: 'dive-new-gas-input',
  templateUrl: './new-gas-input.component.html',
  styleUrl: './new-gas-input.component.scss',
})
export class NewGasInputComponent {
  @Output() newGasSelected = new EventEmitter<BreathingGas>();

  newGasSelectedOption = 'current';
  currentGas: BreathingGas = this.divePlanner.getCurrentGas();
  standardGas: BreathingGas | undefined;
  customGas: BreathingGas = BreathingGas.create(21, 0, 79, this.divePlanner.settings);
  newGas: BreathingGas = this.divePlanner.getCurrentGas();
  StandardGases: BreathingGas[] = BreathingGas.StandardGases;
  optimalGas: BreathingGas = this.divePlanner.getOptimalDecoGas(this.divePlanner.getCurrentDepth());
  isStandardGasDisabled: boolean = this.getStandardGasDisabled();
  isCustomGasDisabled: boolean = this.getCustomGasDisabled();

  constructor(public divePlanner: DivePlannerService) {}

  onGasTypeChange(): void {
    this.calculateNewGas();

    this.isStandardGasDisabled = this.getStandardGasDisabled();
    this.isCustomGasDisabled = this.getCustomGasDisabled();

    this.newGasSelected.emit(this.newGas);
  }

  onStandardGasSelectionChange(): void {
    this.calculateNewGas();
    this.newGasSelected.emit(this.newGas);
  }

  onCustomGasChanged(gas: BreathingGas): void {
    this.customGas = gas;
    this.calculateNewGas();
    this.newGasSelected.emit(this.newGas);
  }

  private calculateNewGas(): void {
    // default it to current gas (e.g. standard is selected but no option picked in dropdown)
    this.newGas = this.divePlanner.getCurrentGas();

    if (this.newGasSelectedOption === 'standard' && this.standardGas !== undefined) {
      this.newGas = this.standardGas;
    }

    if (this.newGasSelectedOption === 'custom') {
      this.newGas = this.customGas;
    }

    if (this.newGasSelectedOption === 'optimal') {
      this.newGas = this.optimalGas;
    }
  }

  private getStandardGasDisabled(): boolean {
    return this.newGasSelectedOption !== 'standard';
  }

  private getCustomGasDisabled(): boolean {
    return this.newGasSelectedOption !== 'custom';
  }
}

<mat-radio-group [(ngModel)]="newGasSelectedOption" (change)="onGasTypeChange()">
  <div class="new-gas-input">
    <div class="new-gas-col">
      <mat-radio-button value="current">
        <div>Current Gas</div>
        <div class="gas-description" [innerHTML]="currentGas.description"></div>
      </mat-radio-button>
      <mat-radio-button
        value="optimal"
        id="optimal-deco-gas-radio"
        matTooltip="The gas with the maximum O2 while staying under {{
          divePlanner.settings.decoPO2Maximum
        }} PO2, and the minimum Helium while staying at an END (Equivalent Narcotic Depth) of <= {{ divePlanner.settings.ENDErrorThreshold }}m">
        <div>Optimal Deco Gas</div>
        <div class="gas-description" [innerHTML]="optimalGas.description"></div>
      </mat-radio-button>
    </div>
    <div class="new-gas-col">
      <div>
        <mat-radio-button value="standard">
          <div>Standard Gas</div>
        </mat-radio-button>
      </div>
      <div>
        <mat-form-field>
          <mat-select
            [(ngModel)]="standardGas"
            hideSingleSelectionIndicator
            (selectionChange)="onStandardGasSelectionChange()"
            [disabled]="isStandardGasDisabled"
            class="standard-gas-dropdown">
            <mat-select-trigger>
              <div>{{ standardGas?.name }}</div>
              <div class="gas-description" [innerHTML]="standardGas?.compositionDescription"></div>
            </mat-select-trigger>
            @for (gas of StandardGases; track gas) {
              <mat-option [value]="gas">
                <div>{{ gas.name }}</div>
                <div class="gas-description" [innerHTML]="gas.compositionDescription"></div>
              </mat-option>
            }
          </mat-select>
        </mat-form-field>
      </div>
    </div>
    <div class="new-gas-col">
      <mat-radio-button value="custom">Custom gas</mat-radio-button>
      <dive-custom-gas-input [disabled]="isCustomGasDisabled" (gasChanged)="onCustomGasChanged($event)"></dive-custom-gas-input>
    </div>
  </div>
</mat-radio-group>

// src/app/components/NewGasInput.tsx
'use client';

import React, { useState, useCallback } from 'react';
import {
  Box,
  Radio,
  RadioGroup,
  FormControlLabel,
  FormControl,
  Select,
  MenuItem,
  Tooltip,
  Paper,
  Typography,
} from '@mui/material';
import { SelectChangeEvent } from '@mui/material/Select';
import CustomGasInput from './CustomGasInput';
import { BreathingGas } from '../dive-planner-service/BreathingGas';
import { useDivePlanner } from '../contexts/DivePlannerContext';

interface NewGasInputProps {
  onNewGasSelected: (gas: BreathingGas) => void;
}

export default function NewGasInput({ onNewGasSelected }: NewGasInputProps) {
  const { divePlanner } = useDivePlanner();
  const settings = divePlanner.settings;

  const [newGasSelectedOption, setNewGasSelectedOption] = useState('current');
  const [standardGasIndex, setStandardGasIndex] = useState<number | ''>('');
  const [customGas, setCustomGas] = useState<BreathingGas>(
    BreathingGas.create(21, 0, 79, settings)
  );

  const currentGas = divePlanner.getCurrentGas();
  const StandardGases = divePlanner.getStandardGases();
  const optimalGas = divePlanner.getOptimalDecoGas(divePlanner.getCurrentDepth());

  const calculateNewGas = useCallback((option: string, stdGasIndex: number | '', custGas: BreathingGas) => {
    let newGas = currentGas;

    if (option === 'standard' && stdGasIndex !== '' && StandardGases[stdGasIndex]) {
      newGas = StandardGases[stdGasIndex];
    } else if (option === 'custom') {
      newGas = custGas;
    } else if (option === 'optimal') {
      newGas = optimalGas;
    }

    onNewGasSelected(newGas);
  }, [currentGas, StandardGases, optimalGas, onNewGasSelected]);

  const handleGasTypeChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const option = event.target.value;
    setNewGasSelectedOption(option);
    calculateNewGas(option, standardGasIndex, customGas);
  };

  const handleStandardGasChange = (event: SelectChangeEvent<number | ''>) => {
    const index = event.target.value as number;
    setStandardGasIndex(index);
    calculateNewGas(newGasSelectedOption, index, customGas);
  };

  const handleCustomGasChanged = useCallback((gas: BreathingGas) => {
    setCustomGas(gas);
    if (newGasSelectedOption === 'custom') {
      onNewGasSelected(gas);
    }
  }, [newGasSelectedOption, onNewGasSelected]);

  const isStandardGasDisabled = newGasSelectedOption !== 'standard';
  const isCustomGasDisabled = newGasSelectedOption !== 'custom';

  return (
    <Paper elevation={2} sx={{ p: 2 }}>
      <FormControl component="fieldset">
        <RadioGroup value={newGasSelectedOption} onChange={handleGasTypeChange}>
          <Box sx={{ display: 'flex', gap: 3, flexWrap: 'wrap' }}>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
              <FormControlLabel
                value="current"
                control={<Radio />}
                label={
                  <Box>
                    <div>Current Gas</div>
                    <Typography variant="body2" color="textSecondary" dangerouslySetInnerHTML={{ __html: currentGas.description }} />
                  </Box>
                }
              />
              <Tooltip title={`The gas with the maximum O2 while staying under ${settings.decoPO2Maximum} PO2, and the minimum Helium while staying at an END (Equivalent Narcotic Depth) of <= ${settings.ENDErrorThreshold}m`}>
                <FormControlLabel
                  value="optimal"
                  control={<Radio />}
                  label={
                    <Box>
                      <div>Optimal Deco Gas</div>
                      <Typography variant="body2" color="textSecondary" dangerouslySetInnerHTML={{ __html: optimalGas.description }} />
                    </Box>
                  }
                />
              </Tooltip>
            </Box>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
              <FormControlLabel value="standard" control={<Radio />} label="Standard Gas" />
              <Select
                value={standardGasIndex}
                onChange={handleStandardGasChange}
                disabled={isStandardGasDisabled}
                displayEmpty
                size="small"
                sx={{ minWidth: 200 }}
              >
                <MenuItem value="" disabled>Select a gas</MenuItem>
                {StandardGases.map((gas, index) => (
                  <MenuItem key={index} value={index}>
                    <Box>
                      <div>{gas.name}</div>
                      <Typography variant="body2" color="textSecondary" dangerouslySetInnerHTML={{ __html: gas.compositionDescription }} />
                    </Box>
                  </MenuItem>
                ))}
              </Select>
            </Box>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
              <FormControlLabel value="custom" control={<Radio />} label="Custom gas" />
              <CustomGasInput
                disabled={isCustomGasDisabled}
                onGasChanged={handleCustomGasChanged}
              />
            </Box>
          </Box>
        </RadioGroup>
      </FormControl>
    </Paper>
  );
}
