// src/src/app/ceiling-chart/ceiling-chart.component.ts
import { Component, Input, OnChanges } from '@angular/core';
import { DivePlannerService } from '../dive-planner-service/DivePlannerService';
import { MatDialog } from '@angular/material/dialog';
import { BreathingGas } from '../dive-planner-service/BreathingGas';
import { GraphDialogComponent } from '../graph-dialog/graph-dialog.component';
import * as Plotly from 'plotly.js-basic-dist-min';

@Component({
  selector: 'dive-ceiling-chart',
  templateUrl: './ceiling-chart.component.html',
  styleUrl: './ceiling-chart.component.scss',
})
export class CeilingChartComponent implements OnChanges {
  @Input() timeAtDepth: number = 0;

  currentDepth: number = this.divePlanner.getCurrentDepth();
  currentGas: BreathingGas = this.divePlanner.getCurrentGas();

  private readonly NEW_DEPTH_COLOR = 'red';
  private readonly PRIMARY_COLOR = '#3F51B5'; // Indigo 500

  constructor(
    private divePlanner: DivePlannerService,
    private dialog: MatDialog
  ) {}

  ngOnChanges(): void {
    const ceilingData = this.divePlanner.getCeilingChartData(this.currentDepth, this.currentGas);
    Plotly.react('ceiling-chart', this.getCeilingChartData(ceilingData), this.getCeilingChartLayout(), this.getCeilingChartOptions());
  }

  public onCeilingChartClick(): void {
    const ceilingData = this.divePlanner.getCeilingChartData(this.currentDepth, this.currentGas);

    this.dialog.open(GraphDialogComponent, {
      data: { trace: this.getCeilingChartData(ceilingData), layout: this.getCeilingChartLayout(), options: this.getCeilingChartOptions() },
      height: '80%',
      width: '80%',
    });
  }

  private getCeilingChartData(data: { time: number; ceiling: number }[]): Plotly.Data[] {
    const x = data.map(d => new Date(1970, 1, 1, 0, 0, d.time, 0));
    const y = data.map(d => d.ceiling);

    return [
      {
        x,
        y,
        type: 'scatter',
        mode: 'lines',
        name: 'Ceiling',
        line: {
          color: this.PRIMARY_COLOR,
          width: 2,
        },
        hovertemplate: `%{y:.0f}m`,
      },
    ];
  }

  private getCeilingChartLayout(): Partial<Plotly.Layout> {
    return {
      autosize: false,
      showlegend: false,
      title: {
        text: 'Ceiling Over Time',
        y: 0.98,
      },
      margin: { l: 35, r: 10, b: 30, t: 20, pad: 10 },
      xaxis: {
        fixedrange: true,
        tickformat: '%H:%M:%S',
      },
      yaxis: {
        fixedrange: true,
        autorange: 'reversed',
      },
      hovermode: 'x unified',
      hoverlabel: {
        bgcolor: 'rgba(200, 200, 200, 0.25)',
        bordercolor: 'rgba(200, 200, 200, 0.4)',
      },
      shapes: [
        {
          type: 'line',
          xref: 'x',
          yref: 'paper',
          x0: new Date(1970, 1, 1, 0, 0, this.timeAtDepth * 60, 0),
          x1: new Date(1970, 1, 1, 0, 0, this.timeAtDepth * 60, 0),
          y0: 0,
          y1: 1,
          line: {
            color: this.NEW_DEPTH_COLOR,
            width: 1,
            dash: 'dot',
          },
        },
      ],
    };
  }

  private getCeilingChartOptions(): Partial<Plotly.Config> {
    return {
      responsive: true,
      displaylogo: false,
      displayModeBar: false,
      autosizable: true,
      scrollZoom: false,
      editable: false,
    };
  }
}

<button (click)="onCeilingChartClick()" class="ceiling-chart">
  <div id="ceiling-chart" class="plotly-graph"></div>
</button>

// src/src/components/charts/CeilingChart.tsx
'use client';

import { useMemo } from 'react';
import dynamic from 'next/dynamic';
import { Box, Typography } from '@mui/material';
import { useDivePlanner } from '@/context/DivePlannerContext';

const Plot = dynamic(() => import('react-plotly.js'), { ssr: false });

const PRIMARY_COLOR = '#3F51B5';

interface CeilingChartProps {
  timeAtDepth: number;
}

export default function CeilingChart({ timeAtDepth }: CeilingChartProps) {
  const { divePlanner, updateTrigger } = useDivePlanner();

  const currentDepth = divePlanner.getCurrentDepth();
  const currentGas = divePlanner.getCurrentGas();

  const chartData = useMemo(() => {
    const data = divePlanner.getCeilingChartData(currentDepth, currentGas);
    const x = data.map(d => Math.floor(d.time / 60)); // Convert to minutes
    const y = data.map(d => d.ceiling);

    return [
      {
        x,
        y,
        type: 'scatter' as const,
        mode: 'lines' as const,
        name: 'Ceiling',
        line: { color: PRIMARY_COLOR, width: 2 },
        hovertemplate: `%{y:.1f}m at %{x}min`,
      },
    ];
  }, [divePlanner, currentDepth, currentGas, updateTrigger]);

  const layout = {
    autosize: true,
    showlegend: false,
    title: { text: 'Ceiling Over Time at Current Depth', y: 0.98 },
    margin: { l: 45, r: 10, b: 40, t: 30, pad: 10 },
    xaxis: {
      fixedrange: true,
      title: { text: 'Time (minutes)' },
    },
    yaxis: {
      fixedrange: true,
      title: { text: 'Ceiling (m)' },
    },
    shapes: timeAtDepth > 0 ? [
      {
        type: 'line' as const,
        x0: timeAtDepth,
        y0: 0,
        x1: timeAtDepth,
        yref: 'paper' as const,
        y1: 1,
        line: {
          color: 'red',
          width: 2,
          dash: 'dash' as const,
        },
      },
    ] : [],
    hovermode: 'x unified' as const,
  };

  const config = {
    responsive: true,
    displaylogo: false,
    displayModeBar: false,
  };

  return (
    <Box>
      <Typography variant="h6" sx={{ mb: 1 }}>
        Ceiling Projection
      </Typography>
      <Box sx={{ height: 300 }}>
        <Plot
          data={chartData}
          layout={layout}
          config={config}
          style={{ width: '100%', height: '100%' }}
        />
      </Box>
    </Box>
  );
}
